-- Add new board roles to UserRole enum
-- VICE_PRESIDENT, SECRETARY, TREASURER, BOARD_MEMBER

ALTER TABLE `users` MODIFY `role` ENUM('SUPER_ADMIN', 'TENANT_ADMIN', 'PRESIDENT', 'VICE_PRESIDENT', 'SECRETARY', 'TREASURER', 'BOARD_MEMBER', 'ORGANIZER', 'JUDGE', 'PARTICIPANT', 'MEMBER') NOT NULL DEFAULT 'PARTICIPANT';
